trigger:
- none

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      condition: eq(variables['dataServices'], 'true')
      displayName: Build and Push ds indirect platform plugin
      inputs:
        targetType: 'inline'
        script: | 
          echo $(sonobuoyVersion)
          sudo curl -L https://github.com/vmware-tanzu/sonobuoy/releases/download/v$(sonobuoyVersion)/sonobuoy_$(sonobuoyVersion)_linux_amd64.tar.gz --output /bin/sonobuoy.tar.gz
          ls /bin/sonobuoy.tar.gz
          file /bin/sonobuoy.tar.gz
          sudo tar -xzf /bin/sonobuoy.tar.gz -C /bin/
          ls /bin/sonobuoy
    - task: Docker@2
      condition: eq(variables['dataServices'], 'true')
      displayName: Build ds-connect plugin
      inputs:
        containerRegistry: arcdscontainerregistry
        repository: arcdscontainerregistry.azurecr.io/ds-pipeline-fail
        command: build
        Dockerfile: 'src/plugins/ds_connect_core/Dockerfile'
        buildContext: 'src/plugins'
        tags: $(dsconnectplatformPluginImageVersion)
        arguments: '--build-arg SONOBUOY_VERSION=$(sonobuoyVersion)'
        addPipelineData: false
    - task: Docker@2
      condition: eq(variables['dataServices'], 'true')
      displayName: Push ds-connect plugin
      inputs:
        command: push
        containerRegistry: arcdscontainerregistry
        repository: arcdscontainerregistry.azurecr.io/ds-pipeline-fail
        tags: $(dsconnectplatformPluginImageVersion)
        addPipelineData: false