trigger:
- none
  
variables:
- name: data-services
  value: yes

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      displayName: Build and Push platform plugin
      inputs:
        targetType: 'inline'
        script: | 
          echo "Sleeping for k8..."
    - task: Bash@3
      condition: eq(variables.data-services, 'no'))
      displayName: Build and Push ds platform plugin
      inputs:
        targetType: 'inline'
        script: | 
          echo "Sleeping for ds indirect..."
    - task: Bash@3
      displayName: Build and Push ds platform plugin
      inputs:
        targetType: 'inline'
        script: | 
          echo "Sleeping for ds direct..."
    - task: Bash@3
      displayName: Build and Push ds platform plugin
      inputs:
        targetType: 'inline'
        script: | 
          echo "Sleeping for k8 cleanup..."