trigger:
- none

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      condition: eq(variables['dataServices'], 'true')
      displayName: Build and Push ds indirect platform plugin
      inputs:
        targetType: 'inline'
        script: | 
          wget -4 https://github.com/vmware-tanzu/sonobuoy/releases/download/v${SONOBUOY_VERSION}/sonobuoy_${SONOBUOY_VERSION}_linux_amd64.tar.gz -O /bin/sonobuoy.tar.gz
          ls /bin/sonobuoy.tar.gz
          file /bin/sonobuoy.tar.gz
          tar -xzf /bin/sonobuoy.tar.gz -C /bin/
          ls /bin/
    - task: Docker@2
      condition: eq(variables['dataServices'], 'true')
      displayName: Build and Push ds direct platform plugin
      inputs:
        containerRegistry: 'arcdscontainerregistry'
        repository: 'arcdscontainerregistry.azurecr.io/ds-pipeline-fail'
        command: 'buildAndPush'
        Dockerfile: 'src/plugins/ds_connect_core/Dockerfile'
        buildContext: 'src/plugins'
        tags: $(dsconnectplatformPluginImageVersion)
        arguments: '--build-arg SONOBUOY_VERSION=$(sonobuoyVersion)'
        addPipelineData: false