trigger:
- none
  
resources:
- repo: self
  
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: task1@2
      displayName: Build and Push platform plugin
      inputs:
        targetType: 'inline'
        script: | 
          echo "Sleeping for k8..."
    # - task: task2@2
    #   displayName: Build and Push ds platform plugin
    #   inputs:
    #     script: 'echo ds platform plugin.' 
    #     addPipelineData: false